# Generated by Django 4.2.2 on 2024-09-26 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stadium',
            name='capacity',
        ),
    ]
