# Generated by Django 4.2.2 on 2024-09-26 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_remove_stadium_capacity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seatassignment',
            old_name='reserver_by',
            new_name='reserved_by',
        ),
    ]
